### ISSUE TITLE
Automation to reset the `main` environment for development

### ISSUE THREAD

**Issue by jazzsequence** [pantheon-systems/plugin-pipeline-example#12]
After the `Tag` workflow runs (and possibly after, or concurrent to #11), we need a workflow that will change the version in all the relevant files from `X.X.X (Date)` and `X.X.X` to `X.X.Y-dev`. This can be merged directly back onto the `main` branch (although for the purpose of testing, perhaps it should be done onto a different branch?).

**Comment by pwtyler** [comment]
this was merged, but the readme part is not yet working.
