### ISSUE TITLE
Investigate/use asset-only updates action from 10up

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/plugin-pipeline-example#16]
https://github.com/10up/action-wordpress-plugin-asset-update

This may need some work/though on how to fold this into our development/release workflow, as this would likely be outside the main => release => tag flow we've sought to establish in contributing.md

**Comment by jazzsequence** [comment]
Done! https://github.com/pantheon-systems/plugin-pipeline-example/blob/main/.github/workflows/build-tag-release.yml
